{"uuid": "d8b3957e-110f-4353-9fb0-883e2b292ac7", "children": ["fd253090-b880-421c-b69a-938f9ce5dc85"], "befores": [{"name": "mobile_os_settings", "status": "passed", "start": 1737832404728, "stop": 1737832404728}], "afters": [{"name": "mobile_os_settings::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Authorization Required\n\n", "trace": "  File \"E:\\Soft\\QA_Python\\qa_hmw19\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"E:\\Soft\\QA_Python\\qa_hmw19\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"E:\\Soft\\QA_Python\\qa_hmw19\\conftest.py\", line 62, in mobile_os_settings\n    browser.driver.get_screenshot_as_png(),\n    ^^^^^^^^^^^^^^\n  File \"E:\\Soft\\QA_Python\\qa_hmw19\\.venv\\Lib\\site-packages\\selene\\core\\_browser.py\", line 34, in driver\n    return self.config.driver\n           ^^^^^^^^^^^^^^^^^^\n  File \"E:\\Soft\\QA_Python\\qa_hmw19\\.venv\\Lib\\site-packages\\selene\\core\\configuration.py\", line 305, in __get__\n    driver = config.build_driver_strategy(config)\n  File \"E:\\Soft\\QA_Python\\qa_hmw19\\.venv\\Lib\\site-packages\\selene\\core\\configuration.py\", line 129, in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n           ~~~~~~~~~~~~~~~~~\n    ...<32 lines>...\n        )\n        ~\n    )()\n    ~^^\n  File \"E:\\Soft\\QA_Python\\qa_hmw19\\.venv\\Lib\\site-packages\\selene\\core\\configuration.py\", line 120, in build_appium_driver\n    return webdriver.Remote(\n           ~~~~~~~~~~~~~~~~^\n        command_executor=(\n        ^^^^^^^^^^^^^^^^^^\n    ...<4 lines>...\n        options=config.driver_options,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"E:\\Soft\\QA_Python\\qa_hmw19\\.venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 227, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        command_executor=command_executor,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        client_config=client_config,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"E:\\Soft\\QA_Python\\qa_hmw19\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 250, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"E:\\Soft\\QA_Python\\qa_hmw19\\.venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 319, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"E:\\Soft\\QA_Python\\qa_hmw19\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"E:\\Soft\\QA_Python\\qa_hmw19\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 196, in check_response\n    raise exception_class(value)\n"}, "start": 1737832415114, "stop": 1737832415227}], "start": 1737832404728, "stop": 1737832415227}